In [1]:
# Example 25: NumPy - Masked Indexing with np.ma.masked_where
import numpy as np

# Creating an array
array = np.array([1, -2, 3, -4, 5])

# Masking elements where values are negative
masked_array = np.ma.masked_where(array < 0, array)

print('Masked Array with Negative Values Hidden:', masked_array)

Masked Array with Negative Values Hidden: [1 -- 3 -- 5]


In [2]:
# Example 15: NumPy - Masked Indexing
import numpy as np

# Creating an array
array = np.array([1, -2, 3, -4, 5])

# Creating a mask for positive values
mask = array > 0

# Applying mask to get only positive values
positive_values = array[mask]

print('Positive Values:', positive_values)

Positive Values: [1 3 5]


In [3]:
# Example 17: NumPy - Linear Space Array
import numpy as np

# Generating a linear space array with evenly spaced values
linear_space = np.linspace(0, 10, 5)

print('Linear Space Array:', linear_space)

Linear Space Array: [ 0.   2.5  5.   7.5 10. ]


In [4]:
# Example 17: NumPy - Indexing with np.where()
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Using np.where to find indices where elements are greater than 25
indices = np.where(array > 25)

print('Indices where elements > 25:', indices)
print('Values where elements > 25:', array[indices])

Indices where elements > 25: (array([2, 3, 4]),)
Values where elements > 25: [30 40 50]


In [5]:
# Example 24: NumPy - Indexing with np.take
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Using np.take to select elements at specific indices
indices = [0, 2, 4]
result = np.take(array, indices)

print('Selected Elements using np.take:', result)

Selected Elements using np.take: [10 30 50]


In [6]:
# Example 7: NumPy - Indexing with Arrays
import numpy as np

# Creating a 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Using arrays for indexing
rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])
indexed_elements = array_2d[rows, cols]

print('Indexed Elements:', indexed_elements)

Indexed Elements: [30 50 70]


In [7]:
# Example 26: NumPy - Flattening a Multi-dimensional Array
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
flattened_array = array_2d.flatten()

print('Flattened Array:', flattened_array)

Flattened Array: [1 2 3 4 5 6]


In [8]:
# Example 4: NumPy - Fancy Indexing
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Selecting specific indices
selected_elements = array[[1, 3, 4]]

print('Selected Elements:', selected_elements)

Selected Elements: [20 40 50]


In [9]:
# Example 22: NumPy - Extract Lower Triangle of a Matrix
import numpy as np

# Creating a square matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extracting the lower triangle (below the main diagonal)
lower_triangle = np.tril(matrix)

print('Lower Triangle of the Matrix:\n', lower_triangle)

Lower Triangle of the Matrix:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [10]:
# Example 16: NumPy - Extracting Diagonal Elements
import numpy as np

# Creating a square matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extracting the main diagonal
diagonal_elements = np.diag(matrix)

print('Diagonal Elements:', diagonal_elements)

Diagonal Elements: [1 5 9]


In [11]:
# Example 4: NumPy - Exponential and Logarithmic Functions
import numpy as np

# Creating an array
array = np.array([1, 2, 3])

# Exponential and logarithmic functions
exp_array = np.exp(array)
log_array = np.log(array)

print('Exponential of Array:', exp_array)
print('Logarithm of Array:', log_array)

Exponential of Array: [ 2.71828183  7.3890561  20.08553692]
Logarithm of Array: [0.         0.69314718 1.09861229]


In [12]:
# Example 14: NumPy - Using Ellipsis (...) in Indexing
import numpy as np

# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Using ellipsis to select all elements along specific axes
result = array_3d[..., 1]  # Selecting the second column in each 2D slice

print('Result using Ellipsis (...):\n', result)

Result using Ellipsis (...):
 [[ 2  4]
 [ 6  8]
 [10 12]]


In [13]:
# Example 20: NumPy - Cumulative Sum and Product
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4])

# Calculating cumulative sum and product
cumulative_sum = np.cumsum(array)
cumulative_product = np.cumprod(array)

print('Cumulative Sum:', cumulative_sum)
print('Cumulative Product:', cumulative_product)

Cumulative Sum: [ 1  3  6 10]
Cumulative Product: [ 1  2  6 24]


In [14]:
# Example 28: NumPy - Conditional Replacement with np.where
import numpy as np

# Creating an array
array = np.array([10, 15, 20, 25, 30])

# Replacing values based on condition
result = np.where(array > 20, 0, array)

print('Array with Values Greater Than 20 Replaced with 0:', result)

Array with Values Greater Than 20 Replaced with 0: [10 15 20  0  0]


In [15]:
# Example 8: NumPy - Conditional Indexing
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6])

# Setting elements that satisfy a condition
array[array % 2 == 0] = -1  # Set even numbers to -1

print('Array after Conditional Indexing:', array)

Array after Conditional Indexing: [ 1 -1  3 -1  5 -1]


In [16]:
# Example 15: NumPy - Concatenation of Arrays
import numpy as np

# Creating arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenating arrays
concatenated_array = np.concatenate((array1, array2))

print('Concatenated Array:', concatenated_array)

Concatenated Array: [1 2 3 4 5 6]


In [19]:
# Example 12: NumPy - Combining Boolean and Fancy Indexing
import numpy as np

# Creating an array
array = np.array([10, 15, 20, 25, 30])

# Boolean condition combined with specific indices
result = array[(array > 10) & (array < 30)][[0, 2]]

print('Combined Boolean and Fancy Indexing Result:', result)

Combined Boolean and Fancy Indexing Result: [15 25]


In [20]:
# Example 19: NumPy - Clipping Array Values
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Clipping values to be between 2 and 4
clipped_array = np.clip(array, 2, 4)

print('Original Array:', array)
print('Clipped Array:', clipped_array)

Original Array: [1 2 3 4 5]
Clipped Array: [2 2 3 4 4]


In [22]:
# Example 9: NumPy - Broadcasting
import numpy as np

# Creating an array
array = np.array([1, 2, 3])

# Broadcasting: Adding a scalar to an array
result = array + 10

print('Original Array:', array)
print('Array after Broadcasting:', result)

Original Array: [1 2 3]
Array after Broadcasting: [11 12 13]


In [23]:
# Example 12: NumPy - Boolean Indexing
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even_numbers = array[array % 2 == 0]

print('Original Array:', array)
print('Even Numbers:', even_numbers)

Original Array: [1 2 3 4 5 6]
Even Numbers: [2 4 6]


In [24]:
# Example 1: NumPy - Basic Indexing and Slicing
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Accessing elements by index
first_element = array[0]
last_element = array[-1]

# Slicing the array
slice_array = array[1:4]

print('First Element:', first_element)
print('Last Element:', last_element)
print('Sliced Array:', slice_array)

First Element: 10
Last Element: 50
Sliced Array: [20 30 40]


In [25]:
# Example 2: NumPy - Basic Arithmetic Operations
import numpy as np

# Creating arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Arithmetic operations
added = np.add(array1, array2)
subtracted = np.subtract(array1, array2)
multiplied = np.multiply(array1, array2)
divided = np.divide(array1, array2)

print('Added:', added)
print('Subtracted:', subtracted)
print('Multiplied:', multiplied)
print('Divided:', divided)

Added: [5 7 9]
Subtracted: [-3 -3 -3]
Multiplied: [ 4 10 18]
Divided: [0.25 0.4  0.5 ]


In [26]:
# Example 1: NumPy - Array Creation Basics
import numpy as np

# Creating arrays with different functions
array_zeros = np.zeros((3, 3))
array_ones = np.ones((2, 2))
array_full = np.full((2, 2), 7)
array_range = np.arange(10)

print('Array of Zeros:\n', array_zeros)
print('Array of Ones:\n', array_ones)
print('Array with All Elements as 7:\n', array_full)
print('Array with Range of Numbers:', array_range)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1.]
 [1. 1.]]
Array with All Elements as 7:
 [[7 7]
 [7 7]]
Array with Range of Numbers: [0 1 2 3 4 5 6 7 8 9]


In [27]:
# Example 18: NumPy - Advanced Slicing with Step in 2D Array
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Slicing every second element in rows and columns
result = array_2d[::2, ::2]

print('Advanced Sliced Array with Step:\n', result)

Advanced Sliced Array with Step:
 [[ 1  3]
 [ 9 11]]


In [28]:
# Example 27: NumPy - Advanced Indexing with Meshgrid
import numpy as np

# Creating 1D arrays
x = np.array([1, 2, 3])
y = np.array([4, 5])

# Creating meshgrid for advanced indexing
X, Y = np.meshgrid(x, y)
indices = np.vstack([X.ravel(), Y.ravel()])

print('Indices for Meshgrid Advanced Indexing:\n', indices)

Indices for Meshgrid Advanced Indexing:
 [[1 2 3 1 2 3]
 [4 4 4 5 5 5]]


In [29]:
# Example 6: NumPy - 3D Array Indexing
import numpy as np

# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Accessing elements in a 3D array
element = array_3d[1, 0, 1]  # Accessing the element at [1, 0, 1]

# Slicing in 3D
slice_3d = array_3d[:, 0, :]

print('Element at (1,0,1):', element)
print('Sliced 3D Array:\n', slice_3d)

Element at (1,0,1): 6
Sliced 3D Array:
 [[1 2]
 [5 6]]


In [30]:
# Example 2: NumPy - 2D Array Indexing
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing individual elements
element = array_2d[1, 2]  # Accessing element at row 1, column 2

# Slicing rows and columns
row_slice = array_2d[0, :]  # First row
column_slice = array_2d[:, 1]  # Second column

print('Element at (1,2):', element)
print('First Row:', row_slice)
print('Second Column:', column_slice)

Element at (1,2): 6
First Row: [1 2 3]
Second Column: [2 5 8]
