In [1]:
# Example 18: NumPy - Meshgrid Creation
import numpy as np

# Creating 1D arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Creating a meshgrid
X, Y = np.meshgrid(x, y)

print('Meshgrid X:\n', X)
print('Meshgrid Y:\n', Y)

Meshgrid X:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Meshgrid Y:
 [[4 4 4]
 [5 5 5]
 [6 6 6]]
