In [1]:
# Example 11: NumPy - Random Array Generation
import numpy as np

# Generating random arrays
random_array = np.random.rand(3, 3)  # Random values in a 3x3 array
normal_array = np.random.randn(3, 3)  # Random values with a normal distribution

print('Random Array:\n', random_array)
print('Normal Distribution Array:\n', normal_array)

Random Array:
 [[0.47574174 0.12270016 0.12027553]
 [0.23610236 0.62959148 0.20959017]
 [0.35495788 0.74341198 0.27527132]]
Normal Distribution Array:
 [[ 0.12182293 -1.83771781  0.48787379]
 [ 1.62780965 -0.08086459 -0.40017731]
 [-0.29522838 -0.67271089  0.60570283]]
